### ISSUE TITLE
Mapping simple media and layered media with MOQ 

### ISSUE THREAD

**Issue by suhasHere** [suhasHere/moq-drafts#54]

**Comment by mzanaty** [comment]
Audio
  Codec: Opus Bitrate: 24kbps Sample Rate: 48kHz Channel Config: Mono Lang: en
Video
  Codec: avc3.42E01E Bitrate: 1Mbps Frame Rate: 30 fps Width: 1280 Height: 720
Video with Simulcast Tracks
  Track: 1 Codec: avc3.42E01E Bitrate: 1Mbps Frame Rate: 30 fps Width: 1280 Height: 720
  Track: 2 Codec: avc3.42E01D Bitrate: 0.5Mbps Frame Rate: 30 fps Width: 640 Height: 360
Video with Temporal Layers in Single Track
  Codec: avc3.42E01E Bitrate: 1.5Mbps Frame Rate: 60 fps Width: 1280 Height: 720
  Layer:0 Subgroup: 0 ObjectID: even
  Layer:1 Subgroup: 1 ObjectID: odd

**Comment by mzanaty** [comment]
Mapping quic streams to decoder jitter buffer
Case 1: One track, No subgroups, ObjectID order
Case 2: One track, Multiple subgroups, ObjectID order
Case 3: Multiple dependent spatial tracks, same fps, ObjectID order in ascending quality track order
Case 4: Multiple dependent temporal tracks, dyadic fps, in timestamp order, or ObjectID*multiplier+offset order
multiplier=2^(maxlayer-max(0,layer-1))
offset=2^(maxlayer-layer) MOD multiplier
